In [2]:
import numpy as np

In [3]:
print('abdcdefg'[2:4])
print('abdcdefg'[slice(2,4)])


dc
dc


A matrix 4 * 4

In [4]:
m_4_4 = np.array(np.arange(16).reshape((4,4)))
m_4_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

One element of the matrix

In [5]:
m_4_4[2,3]

np.int64(11)

Second and fourth rows

In [6]:
m_4_4[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

Second and fourth columns

In [7]:
m_4_4[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

A list of pair of indexes: the fours pairs defining the cells in the diagonal

In [8]:
m_4_4[[0,1,2,3],[0,1,2,3]]

array([ 0,  5, 10, 15])

SUBMATRICES: THREE WAYS

In [9]:
M = m_4_4
M[[1,3]][:,[0,2]]

array([[ 4,  6],
       [12, 14]])

In [10]:
idx = np.ix_([1,3],[0,2])
M[idx]

array([[ 4,  6],
       [12, 14]])

In [11]:
M[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])

FILTERING ROWS AND COLUMNS WITH BOOLEANS

In [12]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
filter_rows = np.zeros(M.shape[0], bool)
filter_rows[[1,2]] = True
print(type(filter_rows))
filter_rows

<class 'numpy.ndarray'>


array([False,  True,  True, False])

Filtering rows

In [14]:
M[np.array([False, True, True, False])]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
M[filter_rows]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Difference with filtering with an np_array: numbers in the list are dealt as indexes of the rows to be selected.

In [16]:
M[np.array([0,1,1,0])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

Filtering columns

In [17]:
M[:, [0,3]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

In [18]:
filter_cols = np.zeros(M.shape[1], bool)
filter_cols[[0,3]] = True
M[:, filter_cols]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

Filtering rows and columns

In [19]:
filter_row_col = np.ix_(filter_rows, filter_cols)
M[filter_row_col]

array([[ 4,  7],
       [ 8, 11]])