In [2]:
from typing import Any

import numpy as np
from numpy import ndarray, dtype, bool

arr = np.arange(0.5,3,0.5)
arr


array([0.5, 1. , 1.5, 2. , 2.5])

Use linspace to generate an array starting at 3, ending at 9, and containing 10 elements.

In [3]:
arr2 = np.linspace(3,9,10)
arr2

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

Generate an array with size 100 evenly spaced between -10 to 10 using linspace function in Numpy.

In [50]:
arr100 = np.linspace(-10, 11, 100)
print(f'size arr100 = {arr100.size}')

size arr100 = 100


Get the element at first row and 2nd column of array y.

In [4]:
y = np.array([[1,4,3],[9,2,7]])
y[0,1]

np.int64(4)

Get the first row of array y.

In [5]:
y[0]

array([1, 4, 3])

In [6]:
y[0,:]

array([1, 4, 3])

Get the last column of array y.

In [7]:
y[:, -1]

array([3, 7])

Get the first and third column of array y.

In [8]:
y[:,[0,2]]

array([[1, 3],
       [9, 7]])

Generate a 3 by 5 array with all the as 0.

In [11]:
zeros1 = np.zeros((3,5))
zeros1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Generate a 5 by 3 array with all the element as 1.

In [13]:
ones1 = np.ones((5,3))
ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Generate a 1D empty array with 3 elements.

In [15]:
empty1 = np.empty(3)
empty1

array([0.e+000, 5.e-324, 1.e-323])

Reassign the fourth element of A to 7. Reassign the first, second, and thrid elements to 1. Reassign the second, third, and fourth elements to 9, 8, and 7.

In [19]:
A = np.array(range(1,7))
A_1 = np.arange(1,7)
A, A_1

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [22]:
A[3] = 7
A[0:3] = np.ones(3)
A

array([1, 1, 1, 7, 5, 6])

In [24]:
A[1:4] = [9,8,7]
A

array([1, 9, 8, 7, 5, 6])

Create a zero array b with shape 2 by 2, and set b = ([1,2], [3,4]) using array indexing.

In [25]:
b = np.zeros((2,2))
b[0,0] = 1
b[0,1] = 2
b[1,0] = 3
b[1,1] = 4
b



array([[1., 2.],
       [3., 4.]])

Create a zero array with size (2, 4).
Change the 2nd column in the above array to 1.

In [55]:
zero_2_4 = np.zeros((2,4))
zero_2_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
zero_2_4[:, 1] = 1
zero_2_4

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

Add and substract 2 from b. Multiply and divide b by 2. Square every element of b. Let c be a scalar. On your own, verify the reflexivity of scalar addition and multiplication: b + c = c + b and cb = bc.

In [27]:
print(b+2)
print(b-2)
print(b*2)
print(b/2)
print(b+2, 2+b)
print(b*2, 2*b)
b**2

[[3. 4.]
 [5. 6.]]
[[-1.  0.]
 [ 1.  2.]]
[[2. 4.]
 [6. 8.]]
[[0.5 1. ]
 [1.5 2. ]]
[[3. 4.]
 [5. 6.]] [[3. 4.]
 [5. 6.]]
[[2. 4.]
 [6. 8.]] [[2. 4.]
 [6. 8.]]


array([[ 1.,  4.],
       [ 9., 16.]])

Compute b + d and b - d.

In [28]:
d = np.array([[3,4],[5,6]])
d

array([[3, 4],
       [5, 6]])

In [30]:
b

array([[1., 2.],
       [3., 4.]])

In [29]:
b + d

array([[ 4.,  6.],
       [ 8., 10.]])

In [31]:
b -d

array([[-2., -2.],
       [-2., -2.]])

Compute the transpose of array b.

In [34]:
transp_b = b.T
b, transp_b

(array([[1., 2.],
        [3., 4.]]),
 array([[1., 3.],
        [2., 4.]]))

Vectorized functions.

In [37]:
x = np.arange(2,20,3)
x_2 = x**2
print(x_2)
x = np.sqrt(x_2)
x

[  4  25  64 121 196 289]


array([ 2.,  5.,  8., 11., 14., 17.])

Check which elements of the array x are larger than 3.

In [42]:
x = np.array([1, 2, 4, 5, 9, 3])
x > 3

array([False, False,  True,  True,  True, False])

Check which elements in x are larger than the corresponding element in y.

In [43]:
y = [0,2,3,1,2,3]
x_y: ndarray[tuple[Any, ...], dtype[bool[bool]]] = x > y
x_y

array([ True, False,  True,  True,  True, False])

Python can index elements of an array that satisfy a logical expression.
Create a variable y that contains all the elements of x that are strictly bigger than 3.

In [46]:
y = x[x > 3]
y

array([4, 5, 9])

Assign all the values of x that are bigger than 3, the value 0.

In [47]:
x[x > 3] = 0
x

array([1, 2, 0, 0, 0, 3])